local M = {}

M.STATUS = {
  PENDING = "PENDING",
  RUNNING = "RUNNING",
  CANCELED = "CANCELED",
  SUCCESS = "SUCCESS",
  FAILURE = "FAILURE",
}

M.CATEGORY = {
  SUMMARY = 'SUMMARY',
  RESULT = 'RESULT',
  RESULT_HANDLER = 'RESULT_HANDLER',
  NOTIFY = 'NOTIFY',
  RERUN = 'RERUN',
  OTHER = 'OTHER',
}

return M
